### PR TITLE
tox/ pipenvTooling refresh

### PR DESCRIPTION
**Pull request by jrabbit**
This PR contains the 2.0 fixes, js testing fixes, other tox/travis fixes,  feel free to squash some of this or have me rewrite the history somehow?

### CODE REVIEW

**Comment by jrabbit** [comment]
SO this would close #19 #22

**Comment by skorokithakis** [comment]
Hey @jrabbit, I'm a new maintainer, could you explain a bit about what this PR does? I'd be happy to merge but right now it looks like the PR is pretty big and it's a lot of disparate functionality checked in, which makes it hard to review.

**Comment by jrabbit** [comment]
yeah no worries there's quite a few changes!
It has working js testing, the rename and the addition of [tox ](https://tox.readthedocs.io/en/latest/) and [pipenv](https://pipenv.readthedocs.io/en/latest/).
tox makes the test matrix locally and on travis.
pipenv is a fancy wrapper for pip that supports a new set of specification (Pipfile) and locking files (Pipfile.lock).

to get a working environment you just run `pipenv sync -d` then you can drop into an activated shell via `pipenv shell`

all the devel dependencies for the js tests were broken so they've been fixed.

I think that covers most of the changes

**Comment by jrabbit** [comment]
oh and invoke was added (tasks.py)
http://docs.pyinvoke.org/en/1.2/

**Comment by skorokithakis** [comment]
Oh that sounds awesome, do you think you can split some stuff off so we can begin to merge? Maybe start with something small?

**Comment by skorokithakis** [comment]
I'm afraid this is way too big to meaningfully review, but I would appreciate piecemeal changes that we can review and merge.

**Pull request closed without merging**
