### PR TITLE
Fix urls import for 2.0

### PR DESCRIPTION
**Pull request by jrabbit**
This should be all we need.

### CODE REVIEW

**Comment by kawasakikou** [comment]
why do not marge this??????

**Comment by kitsunde** [comment]
The tests are failing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jrabbit** [comment]
@kitsunde I think we're ready here. lmk if you have any suggestions/criticisms

**Comment by kitsunde** [comment]
Can you adjust the support list to current supported versions of python https://devguide.python.org/#branchstatus

**Comment by jrabbit** [comment]
@kitsunde I'm not positive travis has 3.7 yet?

**Comment by kitsunde** [comment]
That's fine. :P Whichever ones are readily available.

**Comment by jrabbit** [comment]
Uh so do you want to test against 3.4 and 3.5?

**Comment by kitsunde** [comment]
Yes.

**Comment by jrabbit** [comment]
Huh 3.4 works on my machine maybe have it rerun?

**Comment by jrabbit** [comment]
I think this is ready for merge @kitsunde @gaqzi

**Comment by skorokithakis** [comment]
Can this be merged? The library doesn't work without this.

**Comment by skorokithakis** [comment]
If this project needs help, would you consider adding it to [Code Shelter](https://www.codeshelter.co/) so the maintainers there can help? I realize I'm being impatient, but this PR has been open for more than six months and the library is completely broken in the mean time.

**Comment by skorokithakis** [comment]
Merged, thank you!

**Pull request merged**
